version: '3.8'

services:
  mysql-server:
    image: mysql:8
    container_name: mysql-server
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_USER=user
      - MYSQL_PASSWORD=12345
      - MYSQL_DATABASE=nodeproject
    ports:
      - '3306:3306'
    networks:
      - net-dev
    volumes:
      - data-mysql-nodeproject-vol:/var/lib/mysql

networks:
  net-dev:
    driver: bridge

volumes:
  data-mysql-nodeproject-vol:
